// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeohBcsQsTGh-MoPCPz_Y_C8EIakkHQRI',
    appId: '1:944078662163:web:7f0eda532af313d3b12de6',
    messagingSenderId: '944078662163',
    projectId: 'chat-app-3a607',
    authDomain: 'chat-app-3a607.firebaseapp.com',
    storageBucket: 'chat-app-3a607.appspot.com',
    measurementId: 'G-H1BW6JVFER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Ptsn4FvfdYDUnTUhWomRiGmcFUa2nhE',
    appId: '1:944078662163:android:c90c3d8b494bf998b12de6',
    messagingSenderId: '944078662163',
    projectId: 'chat-app-3a607',
    storageBucket: 'chat-app-3a607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbJMq3gH2Bq9MFeU6g_yOLqd7LwgWVhxE',
    appId: '1:944078662163:ios:6ea959dfadfd190eb12de6',
    messagingSenderId: '944078662163',
    projectId: 'chat-app-3a607',
    storageBucket: 'chat-app-3a607.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbJMq3gH2Bq9MFeU6g_yOLqd7LwgWVhxE',
    appId: '1:944078662163:ios:6ea959dfadfd190eb12de6',
    messagingSenderId: '944078662163',
    projectId: 'chat-app-3a607',
    storageBucket: 'chat-app-3a607.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeohBcsQsTGh-MoPCPz_Y_C8EIakkHQRI',
    appId: '1:944078662163:web:a8bb33897aff2b17b12de6',
    messagingSenderId: '944078662163',
    projectId: 'chat-app-3a607',
    authDomain: 'chat-app-3a607.firebaseapp.com',
    storageBucket: 'chat-app-3a607.appspot.com',
    measurementId: 'G-PWVLKF1RYQ',
  );
}
